import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { HeaderSearchSlot } from "@/components/header-search-slot";
import { Button } from "@/components/ui/button";
import { LogIn, LogOut, NotepadText, User } from "lucide-react";
import { LoginUserGoogle, LogOutUser } from "@/lib/authentication";
import Link from "next/link";
import ListItemsProvider from "@/components/list-provider";
import { getUser } from "@/lib/supabase";
import { DropdownMenu, DropdownMenuContent, DropdownMenuItem, DropdownMenuLabel, DropdownMenuSeparator, DropdownMenuTrigger } from "@/components/ui/dropdown-menu";
import { Toaster } from "@/components/ui/sonner";
import { SpeedInsights } from "@vercel/speed-insights/next"
import { Suspense } from "react";
import { Spinner } from "@/components/ui/spinner";
import Image from "next/image";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <ListItemsProvider>
            <header className="h-[76px]">
              <div className="px-2 py-2 container mx-auto">
                <div className="flex items-center">
                  <div className="flex-none">
                    <Link href="/">
                      <Image src="/logo.svg" alt="logo" width={170} height={20} />
                    </Link>
                  </div>
                  <div className="flex gap-2 grow justify-end items-center">
                    <Suspense>
                      <HeaderSearchSlot />
                    </Suspense>

                    <Button variant="outline" size="icon-lg" asChild>
                      <Link href="/lists">
                          <NotepadText />
                      </Link>
                    </Button>
                    <Suspense fallback={<Button size="icon-lg"><Spinner /></Button>}>
                      <LogInLogOut />
                    </Suspense>
                  </div>
                </div>
              </div>
            </header>
            {children}
            <Toaster richColors />
            <SpeedInsights />
          </ListItemsProvider>
        </body>
    </html>
  );
}

async function LogInLogOut() {
  const user = await getUser();

  if (!user) {
    return (
      <Button onClick={LoginUserGoogle} size="icon-lg">
        <LogIn />
      </Button>
    )
  }

  const userName = user.user_metadata.name;

  return (
    <DropdownMenu>
      <DropdownMenuTrigger asChild>
        <Button size="icon-lg">
          <User />
        </Button>
      </DropdownMenuTrigger>
      <DropdownMenuContent className="w-40" align="end">
        <DropdownMenuLabel>{userName ? userName : 'Mi Cuenta'}</DropdownMenuLabel>
        <DropdownMenuSeparator />
        <DropdownMenuItem onClick={LogOutUser}>
          <LogOut />
          Salir
        </DropdownMenuItem>
      </DropdownMenuContent>
    </DropdownMenu>
  )
}
