const baseMap: Record<string, string[]> = {
  arrugula: ["rucula", "ruculas"],
  mint: ["menta"],
  ny: ["new & york"],
  steak: ["bistec"],
  bacon: ["tocineta", "tocino"],
  chicken: ["pollo"],
  red: ["rojo", "roja"],
  rib: ["costilla", "costillas"],
  short: ["corta", "cortas"],
  hamburguer: ["hamburgesa", "hamburguesa", "burger"],
  squash: ["calabaza", "calabazas"],
  gold: ["dorada", "dorado"],
  acorn: ["bellota"],
  bbq: ["barbeque"],
  ajie: ["aji"],
  smoked: ["ahumado", "ahumada", "ahumadas"],
  choriso: ["chorizo"],
  soft: ["suave"],
  swiss: ["suizo", "suiso"],
  spicy: ["picante"],
  std: ["standard"],
  ext: ["extra", "xtra"],
  reb: ["rebanado", "rebanados", "rebanada", "rebanadas", "slice", "slices", "rodajas", "en & mitad", "mitades", "sliced", "partidos"],
  artisian: ["artesana"],
  cong: ["congelada", "congelado"],
  blue: ["azul"],
  crumbled: ["desmenuzado", "desmenuzada", "en & trozos", "diced"],
  herb: ["hierba", "herbs", "hierbas"],
  herbal: ["hierbas"],
  wedge: ["cuña"],
  untable: ["spreadable"],
  cream: ["crema"],
  cheese: ["queso"],
  mozzarella: ["mozarella"],
  flounder: ["platija"],
  cod: ["bacalao"],
  fillet: ["filete"],
  sticks: ["palitos", "deditos"],
  seafood: ["mar", "marisco"],
  spinach: ["espinaca", "espinacas"],
  tuna: ["atun"],
  squid: ["calamar"],
  blackberry: ["mora", "blackberries", "moras"],
  ring: ["anilla", "anillo"],
  mandarina: ["clementina"],
  carnation: ["evaporada"],
  zero: ["sin"],
  bebible: ["liquido", "liquid"],
  banana: ["guineo"],
  greek: ["griego"],
  kids: ["niños", "ninos"],
  activia: ["dannon"],
  org: ["organico"],
  margarina: ["mantequilla", "butter"],
  vanilla: ["vainilla"],
  dairy: ["lactosa", "lacteo"],
  peach: ["durazno", "melocoton"],
  pastel: ["bizcocho", "biscocho"],
  string: ["palitos", "palito"],
  green: ["verde", "verdes"],
  donuts: ["donas"],
  maracuya: ["chinola"],
  english: ["ingles"],
  zumo: ["jugo", "juice"],
  blueberry: ["arandano", "blueberries", "arandanos"],
  yaniqueque: ["pastelitos"],
  veggie: ["vegetariano", "vegetariana"],
  flatbread: ["pan & plano"],
  sesamo: ["sesame"],
  ezekiel: ["ezequiel"],
  decaffeinato: ["descafeinado"],
  big: ["grande", "grandes"],
  tea: ["te"],
  iced: ["frio"],
  lemon: ["limon"],
  white: ["blanco"],
  filter: ["filtro"],
  cookies: ["galletas", "cookie"],
  honey: ["miel"],
  peanut: ["mani"],
  corn: ["maiz"],
  oats: ["avena"],
  almond: ["almendra"],
  zucaritas: ["zucarita", "cereal & frosted & kelloggs"],
  cinnamon: ["canela"],
  frosted: ["azucarado"],
  spray: ["aerosol"],
  virgin: ["virgen"],
  molido: ["en & polvo", "molida", "fina"],
  garlic: ["ajo"],
  broth: ["sopa", "caldo"],
  sopita: ["caldo"],
  refinada: ["alta & pureza"],
  fortigrow: ["crecimiento"],
  balsamic: ["balsamico"],
  ranchero: ["baldom"],
  duo: ["doble"],
  powder: ["polvo"],
  "de & coccion": ["para & cocinar", "de & cocinar"],
  nutmeg: ["nuez & moscada"],
  pink: ["rosado", "rosada"],
  paprika: ["pimenton"],
  sea: ["marino", "marina"],
  salt: ["sal"],
  coarse: ["gruesa"],
  fine: ["fina"],
  greenland: ["lucas & perez"],
  hierbabuena: ["hierba & buena"],
  rosa: ["flor"],
  strawberry: ["fresa", "fresas"],
  vegetal: ["de & soya"],
  avocado: ["aguacate"],
  oil: ["aceite"],
  cider: ["sidra"],
  walnut: ["nuez", "nueces", "walnuts"],
  cherry: ["cereza", "cerezas"],
  grape: ["uva", "uvas"],
  apple: ["manzana", "manzanas"],
  raspberry: ["frambuesa", "frambuesas"],
  pineapple: ["pina"],
  funda: ["sobre"],
  leche: ["alimento & lacteo"],
  nutriforte: ["en & polvo"],
  "corn & flakes": ["hojuelas & maiz", "hojuelas & de & maiz"],
  himalaya: ["sal & rosada"],
  frosting: ["glaseado & de & crema", "glaseado"],
  chip: ["chispas"],
  musclemilk: ["muscle & milk"],
  bioeva: ["bio & eva"],
  medie: ["mediano"],
  ketchup: ["catchup"],
  lasagne: ["lasagna"],
  linguine: ["linguini"],
  squeeze: ["dispenser"],
  spaguetti: ["espaguetti", "espagueti", "spaghetti"],
  baking: ["hornear"],
  edulcorante: ["endulzante"],
  "azucar & refinada": ["azucar & blanca", "azucar & refino"],
  stevia: ["azucar & dietetica", "endulzante"],
  "sin & gluten": ["s & gluten"],
  "leche & rica": ["leche & entera & rica"],
  "salami & super & especial": ["salami & induveca"],
  tiny: ["peq", "pequeno"],
  olive: ["aceitunas", "olives"],
  pickles: ["encurtidos"],
  vainitas: ["habichuelas"],
  tomato: ["tomate", "tomatoes", "tomates"],
  light: ["ligera"],
  mushroom: ["champinones", "hongos"],
  meat: ["carne"],
  one: ["1", "uno"],
  two: ["2", "dos"],
  three: ["3", "tres"],
  four: ["4", "cuatro"],
  five: ["5", "cinco"],
  six: ["6", "seis"],
  seven: ["7", "siete"],
  eight: ["8", "ocho"],
  nine: ["9", "nueve"],
  french: ["frances"],
  basil: ["albahaca"],
  original: ["tradicional"],
  vegetale: ["verdura"],
  hearts: ["heart", "corazon"],
  "con & ajo": ["al & ajillo", "c/ajo"],
  deshuesada: ["sin & hueso", "sin & espinas", "deshuesado"],
  onion: ["cebolla", "onions", "cebollas"],
  roasted: ["tostado", "asado"],
  chestnut: ["castana", "castanas"],
  guisantes: ["petit & pois", "guisante"],
  sweet: ["dulce", "dulces"],
  "petit & pois": ["guisantes & dulces"],
  oyster: ["ostras", "oysters"],
  coconut: ["coco"],
  sprouts: ["brotes", "sprout", "brote"],
};

export const synonyms: Record<string, string[]> = {};
for (const [base, syns] of Object.entries(baseMap)) {
  const group = [base, ...syns];
  for (const w of group) {
    synonyms[w] = group.filter((x) => x !== w);
  }
}
