import { plural } from "pluralize";
import { pluralizeEs } from "./pluralize-es";

const baseMap: Record<string, string[]> = {
  arrugula: ["rucula"],
  mint: ["menta"],
  ny: ["new & york"],
  steak: ["bistec"],
  bacon: ["tocineta", "tocino"],
  chicken: ["pollo"],
  red: ["rojo", "roja"],
  rib: ["costilla"],
  short: ["corta"],
  hamburguer: ["hamburgesa", "hamburguesa", "burger"],
  squash: ["calabaza"],
  gold: ["dorada", "dorado"],
  acorn: ["bellota"],
  bbq: ["barbeque"],
  ajie: ["aji"],
  smoked: ["ahumado", "ahumada"],
  choriso: ["chorizo"],
  soft: ["suave"],
  swiss: ["suizo", "suiso"],
  spicy: ["picante"],
  std: ["standard"],
  ext: ["extra", "xtra"],
  reb: [
    "rebanado",
    "rebanada",
    "slice",
    "slices",
    "rodajas",
    "en & mitad",
    "mitades",
    "sliced",
    "partido",
  ],
  artisian: ["artesana"],
  cong: ["congelada", "congelado"],
  blue: ["azul"],
  crumbled: ["desmenuzado", "desmenuzada", "en & trozos", "diced"],
  herb: ["hierba", "herbs", "herbal"],
  wedge: ["cuña"],
  untable: ["spreadable"],
  cream: ["crema"],
  cheese: ["queso"],
  mozzarella: ["mozarella"],
  flounder: ["platija"],
  cod: ["bacalao"],
  fillet: ["filete"],
  stick: ["palito", "dedito", "string"],
  seafood: ["mar", "marisco"],
  spinach: ["espinaca"],
  tuna: ["atun"],
  squid: ["calamar"],
  blackberry: ["mora"],
  ring: ["anilla", "anillo"],
  mandarina: ["clementina"],
  carnation: ["evaporada"],
  zero: ["sin"],
  bebible: ["liquido", "liquid"],
  banana: ["guineo"],
  greek: ["griego"],
  kid: ["nino"],
  activia: ["dannon"],
  org: ["organico"],
  margarina: ["mantequilla", "butter"],
  vanilla: ["vainilla"],
  dairy: ["lactosa", "lacteo"],
  peach: ["durazno", "melocoton"],
  pastel: ["bizcocho", "biscocho"],
  green: ["verde"],
  donuts: ["donut", "dona"],
  maracuya: ["chinola"],
  english: ["ingles"],
  zumo: ["jugo", "juice"],
  blueberry: ["arandano", "arandanos"],
  yaniqueque: ["pastelito"],
  veggie: ["vegetariano", "vegetariana"],
  flatbread: ["pan & plano"],
  sesamo: ["sesame"],
  ezekiel: ["ezequiel"],
  decaffeinato: ["descafeinado"],
  big: ["grande"],
  tea: ["te"],
  iced: ["frio"],
  lemon: ["limon"],
  white: ["blanco", "blanca"],
  filter: ["filtro"],
  cookie: ["galleta", "crisp"],
  honey: ["miel"],
  peanut: ["mani"],
  corn: ["maiz"],
  oats: ["avena"],
  almond: ["almendra"],
  zucarita: ["cereal & frosted & kelloggs"],
  cinnamon: ["canela"],
  frosted: ["azucarado"],
  spray: ["aerosol"],
  virgin: ["virgen"],
  molido: ["en & polvo", "molida", "fina"],
  garlic: ["ajo"],
  broth: ["sopa"],
  sopita: ["caldo"],
  refinada: ["alta & pureza"],
  fortigrow: ["crecimiento"],
  balsamic: ["balsamico"],
  ranchero: ["baldom"],
  duo: ["doble"],
  powder: ["polvo"],
  "de & coccion": ["para & cocinar", "de & cocinar"],
  nutmeg: ["nuez & moscada"],
  pink: ["rosado", "rosada"],
  paprika: ["pimenton"],
  sea: ["marino", "marina"],
  salt: ["sal"],
  coarse: ["gruesa"],
  fine: ["fina"],
  greenland: ["lucas & perez"],
  hierbabuena: ["hierba & buena"],
  rosa: ["flor"],
  strawberry: ["fresa"],
  vegetal: ["de & soya"],
  avocado: ["aguacate"],
  oil: ["aceite"],
  cider: ["sidra"],
  walnut: ["nuez", "nues", "nut"],
  cherry: ["cereza"],
  grape: ["uva"],
  apple: ["manzana"],
  raspberry: ["frambuesa"],
  pineapple: ["pina"],
  funda: ["sobre"],
  leche: ["alimento & lacteo"],
  nutriforte: ["lacteo & en & polvo"],
  "corn & flakes": ["hojuelas & maiz", "hojuelas & de & maiz"],
  himalaya: ["sal & rosada"],
  frosting: ["glaseado & de & crema", "glaseado"],
  chip: ["chispa"],
  musclemilk: ["muscle & milk"],
  bioeva: ["bio & eva"],
  medie: ["mediano"],
  ketchup: ["catchup"],
  lasagne: ["lasagna"],
  linguine: ["linguini"],
  squeeze: ["dispenser"],
  spaguetti: ["espaguetti", "espagueti", "spaghetti"],
  baking: ["hornear"],
  edulcorante: ["endulzante"],
  "azucar & refinada": ["azucar & blanca", "azucar & refino"],
  stevia: ["azucar & dietetica", "endulzante"],
  "sin & gluten": ["s & gluten"],
  "leche & rica": ["leche & entera & rica"],
  "salami & super & especial": ["salami & induveca"],
  tiny: ["peq", "pequeno"],
  olive: ["aceituna"],
  pickles: ["encurtido"],
  vainitas: ["habichuela"],
  tomato: ["tomate"],
  light: ["ligera"],
  mushroom: ["champinon", "hongo"],
  meat: ["carne"],
  one: ["1", "uno"],
  two: ["2", "dos"],
  three: ["3", "tres"],
  four: ["4", "cuatro"],
  five: ["5", "cinco"],
  six: ["6", "seis"],
  seven: ["7", "siete"],
  eight: ["8", "ocho"],
  nine: ["9", "nueve"],
  french: ["frances", "francesa"],
  basil: ["albahaca"],
  original: ["tradicional"],
  vegetale: ["verdura"],
  hearts: ["heart", "corazon"],
  "con & ajo": ["al & ajillo", "c/ajo"],
  deshuesada: ["sin & hueso", "sin & espinas", "deshuesado"],
  onion: ["cebolla"],
  roasted: ["tostado", "asado", "rostizado", "rostizada", "asada", "tostada"],
  chestnut: ["castana"],
  guisantes: ["petit & pois", "guisante"],
  sweet: ["dulce"],
  "petit & pois": ["guisantes & dulces"],
  oyster: ["ostra"],
  coconut: ["coco"],
  sprout: ["brote"],
  seed: ["semilla"],
  salted: ["salada", "salado", "con & sal"],
  hazelnut: ["avellana"],
  "sopa & instantanea": ["sopa & ramen"],
  shelled: ["pelado", "pelada"],
  mix: ["mixed", "mixto", "mixta", "mezcla"],
  toasted: ["tostado", "tostada"],
  inuts: ["imperial & nuts", "implerial & nuts"],
  lightly: ["bajo & en", "low"],
  cacao: ["chocolate"],
  kitkat: ["kit & kat"],
  mym: ["m&m", "m & m"],
  kiss: ["besito", "kisse"],
  teddy: ["osito"],
  chicle: ["goma & de & mascar"],
  chalaca: ["caramelo & barrilete"],
  style: ["estilo"],
  teeth: ["diente"],
  american: ["americano", "americana"],
  italian: ["italiano", "italiana"],
};

function pluralizeWord(word: string) {
  if (word.includes("&")) {
    return [word];
  }
  const variants = new Set<string>();
  variants.add(plural(word) ? plural(word) : word);
  variants.add(pluralizeEs(word) ? pluralizeEs(word) : word);
  return [...variants];
}

for (const [base, syns] of Object.entries(baseMap)) {
  const allSyns = [...syns, base];
  allSyns.forEach((syn) => {
    allSyns.push(...pluralizeWord(syn));
  });

  baseMap[base] = Array.from(new Set<string>([...allSyns]));
}

export const synonyms: Record<string, string[]> = {};
for (const [base, syns] of Object.entries(baseMap)) {
  const group = [base, ...syns];
  for (const w of group) {
    synonyms[w] = group.filter((x) => x !== w);
  }
}
