const baseMap: Record<string, string[]> = {
  arrugula: ["rucula", "ruculas"],
  mint: ["menta"],
  ny: ["new & york"],
  steak: ["bistec"],
  bacon: ["tocineta", "tocino"],
  chicken: ["pollo"],
  red: ["rojo", "roja"],
  rib: ["costilla", "costillas"],
  short: ["corta", "cortas"],
  hamburguer: ["hamburgesa", "hamburguesa", "burger"],
  squash: ["calabaza", "calabazas"],
  gold: ["dorada", "dorado"],
  acorn: ["bellota"],
  bbq: ["barbeque"],
  ajie: ["aji"],
  smoked: ["ahumado", "ahumada"],
  choriso: ["chorizo"],
  soft: ["suave"],
  swiss: ["suizo", "suiso"],
  spicy: ["picante"],
  std: ["standard"],
  ext: ["extra", "xtra"],
  reb: ["rebanado", "rebanada"],
  artisian: ["artesana"],
  cong: ["congelada", "congelado"],
  blue: ["azul"],
  crumbled: ["desmenuzado", "desmenuzada"],
  herb: ["hierba", "herbs", "hierbas"],
  herbal: ["hierbas"],
  wedge: ["cuña"],
  untable: ["spreadable"],
  cream: ["crema"],
  cheese: ["queso"],
  mozzarella: ["mozarella"],
  flounder: ["platija"],
  cod: ["bacalao"],
  fillet: ["filete"],
  sticks: ["palitos", "deditos"],
  seafood: ["mar", "marisco"],
  spinach: ["espinaca", "espinacas"],
  tuna: ["atun"],
  squid: ["calamar"],
  blackberry: ["mora", "blackberries", "moras"],
  ring: ["anilla", "anillo"],
  mandarina: ["clementina"],
  carnation: ["evaporada"],
  zero: ["sin"],
  bebible: ["liquido"],
  banana: ["guineo"],
  greek: ["griego"],
  kids: ["niños", "ninos"],
  activia: ["dannon"],
  org: ["organico"],
  margarina: ["mantequilla"],
  vanilla: ["vainilla"],
  dairy: ["lactosa", "lacteo"],
  peach: ["durazno"],
  pastel: ["bizcocho", "biscocho"],
  string: ["palitos", "palito"],
  green: ["verde", "verdes"],
  donuts: ["donas"],
  maracuya: ["chinola"],
  english: ["ingles"],
  zumo: ["jugo"],
  blueberry: ["arandano", "blueberries", "arandanos"],
  yaniqueque: ["pastelitos"],
  veggie: ["vegetariano", "vegetariana"],
  flatbread: ["pan & plano"],
  sesamo: ["sesame"],
  ezekiel: ["ezequiel"],
  decaffeinato: ["descafeinado"],
  big: ["grande", "grandes"],
  tea: ["te"],
  iced: ["frio"],
  lemon: ["limon"],
  white: ["blanco"],
  filter: ["filtro"],
  cookies: ["galletas", "cookie"],
  honey: ["miel"],
  peanut: ["mani"],
  butter: ["mantequilla"],
  corn: ["maiz"],
  oats: ["avena"],
  almond: ["almendra"],
  zucaritas: ["zucarita", "cereal & frosted & kelloggs"],
  cinnamon: ["canela"],
  frosted: ["azucarado"],
  spray: ["aerosol"],
  virgin: ["virgen"],
  molido: ["en & polvo"],
  garlic: ["ajo"],
  broth: ["sopa", "caldo"],
  sopita: ["caldo"],
  refinada: ["alta & pureza"],
};

export const synonyms: Record<string, string[]> = {};
for (const [base, syns] of Object.entries(baseMap)) {
  const group = [base, ...syns];
  for (const w of group) {
    synonyms[w] = group.filter((x) => x !== w);
  }
}
