import { plural } from "pluralize";
import { PERMITED_STOP_WORDS, STOP_WORDS } from "./stopwords";
import { pluralizeEs } from "./pluralize-es";

type SynonymsBase = {
  synonyms: string[];
  query: string[];
};

type WithId = SynonymsBase & {
  id: string;
  complex?: never;
};

type WithComplex = SynonymsBase & {
  complex: string[];
  id?: never;
};

type BaseOnly = SynonymsBase & {
  id?: never;
  complex?: never;
};

type Synonym = WithId | WithComplex | BaseOnly;

const base: Array<Synonym> = [
    { synonyms: ["congelado", "congelada", "frozen", "cong"], query: ["cong:*", "frozen:*"] },
    { synonyms: ["sopa instantanea", "ramen"], query: ["sopa:* & instantanea:*", "ramen:*"] },
    { synonyms: ["sin", "free", "zero", "non", "cero", "0"], query: ["sin", "s", "free:*", "zero", "non", "cero", "0", "libre"], id: "sin" },
    { synonyms: ["para", "for"], query: ["para", "for", "p"]},
    { synonyms: ["lactosa", "lacteo", "dairy"], query: ["lactosa:*", "lacteo:*", "dair:*"], id: "lact"},
    { synonyms: ["deslactosada", "deslactosado"], complex: ["sin", "lact"], query: ["deslactosad:*"]},
    { synonyms: ["rebanado", "rebanada", "slice", "rodaja", "en & mitad", "mitade", "sliced", "partido", "trozo", "reb", "cortado", "cortada"], query: ["reb:*", "slice:*", "rodaj:*", "en & mitad:*", "mitade:*", "partid:*", "troz:*", "cortad:*"]},
    { synonyms: ["rucula", "arrugula"], query: ["rucula:*", "arrugula:*"] },
    { synonyms: ["menta", "mint"], query: ["ment:*", "mint:*"], id: "menta"},
    { synonyms: ["flavor", "sabor"], query: ["flavor:*", "sabor:*"], id: "sabor"},
    { synonyms: ["freshmint", "sabor menta", "sabor a menta"], query: ["freshmint"], complex: ["sabor", "menta"]},
    { synonyms: ["new york", "ny"], query: ["new <-> york", "ny"]},
    { synonyms: ["queso", "cheese"], query: ["ques:*", "chees:*"], id: "queso"},
    { synonyms: ["bebibl", "bebible", "liquido", "liquid"], query: ["bebibl:*", "liquid:*"], id: "liquido"},
    { synonyms: ["steak", "bistec"], query: ["steak:*", "bistec:*"]},
    { synonyms: ["bacon", "tocineta", "tocino"], query: ["baco:*", "tocin:*"]},
    { synonyms: ["chicken", "pollo"], query: ["chick:*", "pollo:*"]},
    { synonyms: ["rojo", "roja", "colorada", "red"], query: ["red:*", "roj:*", "colorad:*"], id: "red"},
    { synonyms: ["rib", "costilla"], query: ["rib:*", "costill:*"]},
    { synonyms: ["short", "corto", "corta"], query: ["shor:*", "cort:*"]},
    { synonyms: ["hamburguer", "hamburgesa", "hamburguesa", "burger", "burguer", "hamburger"], query: ["hamburg:*", "burger:*", "burguer:*"]},
    { synonyms: ["squash", "calabaza"], query: ["squas:*", "calabaz:*"]},
    { synonyms: ["gold", "dorado", "dorada", "golden"], query: ["gold:*", "dorad*"]},
    { synonyms: ["acorn", "bellota"], query: ["acorn", "bellot:*"]},
    { synonyms: ["bbq", "barbeque"], query: ["bbq:*", "barbeq:*"]},
    { synonyms: ["ajie", "aji"], query: ["aji:*", "pimiento"]},
    { synonyms: ["smoked", "ahumado", "ahumada", "ahum", "smoke"], query: ["ahum:*", "smoke:*"]},
    { synonyms: ["choriso", "chorizo"], query: ["chori:*"]},
    { synonyms: ["soft", "suave"], query: ["soft:*", "suav:*"]},
    { synonyms: ["swiss", "suizo", "suiso"], query: ["swis:*", "suiz:*", "suis:*"]},
    { synonyms: ["spicy", "picante", "spice"], query: ["spicy:*", "picante:*", "spice"]},
    { synonyms: ["std", "standard"], query: ["std:*", "standar:*", "estandar:*"]},
    { synonyms: ["ext", "extra", "xtra", "mas"], query: ["ext:*", "xtra:*", "mas"]},
    { synonyms: ["jugo", "juice", "zumo", "nectar"], query: ["zumo", "jugo", "juice", "nectar"], id: "jugo"},
    { synonyms: ["blueberry", "arandano", "cranberry", "blue berry", "cramberry"], query: ["blueberr:*", "arandan:*", "cranberr:*", "cramberry", "blue & berry"]},
    { synonyms: ["yaniqueque", "pastelito"], query: ["yaniquequ:*", "pastelit:*"]},
    { synonyms: ["veggie", "vegetariano", "vegetariana", "vegano", "vegana", "vegan"], query: ["veggi:*", "vegetarian:*", "vegi:*", "vegan:*"]},
    { synonyms: ["flatbread", "pan plano"], query: ["flatbrea:*", "pan & plano"]},
    { synonyms: ["sesamo", "sesame", "ajonjoli"], query: ["sesam:*", "ajonjoli"]},
    { synonyms: ["ezekiel", "ezequiel"], query: ["ezeki:*", "ezequi:*"]},
    { synonyms: ["decaffeinato", "descafeinado", "decaffeinato", "decafeinado", "descaf", "decaf"], query: ["decaf:*", "descaf:*"]},
    { synonyms: ["big", "grande", "largo", "larga", "large"], query: ["big:*", "grande:*", "largo", "larga", "large"]},
    { synonyms: ["tiny", "peq", "pequeno", "small"], query: ["tiny", "peq:*", "small"]},
    { synonyms: ["tea", "te"], query: ["tea", "te"]},
    { synonyms: ["iced", "frio", "fria"], query: ["iced:*", "fri:*"]},
    { synonyms: ["lemon", "limon", "lima", "lime"], query: ["limon", "lima", "lemon", "lime"], id: "limon"},
    { synonyms: ["white", "blanco", "blanca"], query: ["white", "blanc:*"], id: "white"},
    { synonyms: ["filter", "filtro"], query: ["filtr:*", "filter"]},
    { synonyms: ["cookie", "galleta", "crisp", "gallet", "cooki"], query: ["cooki:*", "gallet:*", "crisp"], id: "galleta"},
    { synonyms: ["honey", "miel"], query: ["honey", "miel"]},
    { synonyms: ["peanut", "mani"], query: ["peanu:*", "mani:*"]},
    { synonyms: ["corn", "maiz"], query: ["corn", "maiz"]},
    { synonyms: ["oat", "avena"], query: ["oat:*", "avena:*"]},
    { synonyms: ["almond", "almendra", "walmond", "almnd"], query: ["almond:*", "almendra:*", "walmond:*", "almnd"]},
    { synonyms: ["zucarita"], query: ["zucarita", "cereal & frosted & kelloggs"]},
    { synonyms: ["cinnamon", "canela"], query: ["cinnamon", "canela:*"]},
    { synonyms: ["frosted", "azucarado", "azucarada"], query: ["frosted", "azucarad:*"]},
    { synonyms: ["spray", "aerosol", "rociador", "espray"], query: ["spray", "aerosol", "rociador", "espray"]},
    { synonyms: ["virgin", "virgen"], query: ["virgin", "virgen"]},
    { synonyms: ["molido", "en polvo", "molida", "fina", "fino", "fine", "grinder"], query: ["molid:*", "polvo", "fina", "fino", "fine", "grinder"]},
    { synonyms: ["shredded", "rallado", "rallada", "shred"], query: ["shred:*", "rallad:*"]},
    { synonyms: ["artisian", "artesana", "artesanal", "handmade"], query: ["artisian", "artesan:*", "handmade"]},
    { synonyms: ["blue", "azul"], query: ["blue", "azul"]},
    { synonyms: ["crumbled", "desmenuzado", "desmenuzada", "en trozos", "diced"], query: ["crumbled", "desmenuzad:*", "en & trozos", "diced"]},
    { synonyms: ["herb", "hierba", "herbs", "herbal", "yerba"], query: ["herb:*", "hierb:*", "yerb:*"], id: "hierba"},
    { synonyms: ["wedge", "cuna"], query: ["wedge", "cuna"]},
    { synonyms: ["untable", "spreadable", "spread"], query: ["untable", "spread:*"]},
    { synonyms: ["cream", "crema", "creme", "creamer"], query: ["cream:*", "crem:*"], id: "cream"},
    { synonyms: ["mozzarella", "mozarella"], query: ["mozzarella", "mozarella"]},
    { synonyms: ["parmesan", "parmesano", "parmesana"], query: ["parmesan:*"]},
    { synonyms: ["flounder", "platija"], query: ["flounder", "platija"]},
    { synonyms: ["cod", "bacalao"], query: ["cod", "bacalao"]},
    { synonyms: ["fillet", "filete"], query: ["fillet:*", "filet:*"]},
    { synonyms: ["ribeye", "rib eye"], query: ["ribeye", "rib & eye"]},
    { synonyms: ["stick", "palito", "dedito", "string", "barrita"], query: ["stick:*", "palito", "dedito", "string:*", "barrita"]},
    { synonyms: ["seafood", "marisco"], query: ["seafood", "marisco"]},
    { synonyms: ["spinach", "espinaca"], query: ["spinach:*", "espinac:*"]},
    { synonyms: ["tuna", "atun"], query: ["tuna", "atun"]},
    { synonyms: ["squid", "calamar"], query: ["squid:*", "calamar:*"]},
    { synonyms: ["blackberry", "mora", "black berry"], query: ["blackber:*", "mora", "black & berry"]},
    { synonyms: ["dulce", "sweet", "tierno"], query: ["dulce", "sweet:*", "tierno"], id: "dulce"},
    { synonyms: ["guisante", "petit pois", "guisantes dulces", "guisante dulce", "guisante dulces"], query: ["guisante:*", "petit:* & poi:*"]},
    { synonyms: ["oyster", "ostra"], query: ["oyster:*", "ostra"]},
    { synonyms: ["coconut", "coco"], query: ["coconut", "coco"]},
    { synonyms: ["sprout", "brote"], query: ["sprout:*", "brote"]},
    { synonyms: ["seed", "semilla"], query: ["seed", "semilla"]},
    { synonyms: ["with", "con", "al", "y"], query: ["with", "con", "al", "c", "y", "and", "w"], id: "con"},
    { synonyms: ["sal", "salt"], query: ["sal", "salt:*"], id: "sal"},
    { synonyms: ["salted", "salada", "salado"], query: ["salted", "salad:*"], complex: ["con", "sal"]},
    { synonyms: ["hazelnut", "avellana", "noisette"], query: ["hazelnut:*", "avellana:*"]},
    { synonyms: ["shelled", "pelado", "pelada"], query: ["shelled:*", "pelad:*"]},
    { synonyms: ["mix", "mixed", "mixto", "mixta", "mezcla"], query: ["mix:*", "mezcl:*"]},
    { synonyms: ["ring", "anilla", "anillo"], query: ["ring", "anill:*"]},
    { synonyms: ["mandarina", "clementina"], query: ["mandarina", "clementina"]},
    { synonyms: ["carnation", "evaporada"], query: ["carnation", "evaporad:*"]},
    { synonyms: ["banana", "guineo"], query: ["banana:*", "guineo:*"]},
    { synonyms: ["greek", "griego"], query: ["greek:*", "griego:*"]},
    { synonyms: ["kid", "nino", "nina"], query: ["kid:*", "nino", "nina"]},
    { synonyms: ["activia", "dannon"], query: ["activia", "dannon"]},
    { synonyms: ["org", "organico", "organica", "orgain"], query: ["org:*"]},
    { synonyms: ["margarina", "mantequilla", "butter"], query: ["margarin:*", "mantequilla", "butte:*"], id: "mantequilla"},
    { synonyms: ["vanilla", "vainilla"], query: ["vanilla:*", "vainilla:*"]},
    { synonyms: ["peach", "durazno", "melocoton"], query: ["peach:*", "durazno", "melocoton:*"]},
    { synonyms: ["pastel", "bizcocho", "biscocho"], query: ["pastel", "bizcocho:*", "biscocho:*"]},
    { synonyms: ["green", "verde", "geen"], query: ["green:*", "verde"], id: "verde"},
    { synonyms: ["pea", "guandule"], query: ["pea", "guandule:*"]},
    { synonyms: [""], query: ["buen:*"], id: "buena"},
    { synonyms: ["hierbabuena", "hierba buena"], query: ["hierbabuena", "hierba & buena"], complex: ["hierba", "buena"]},
    { synonyms: ["rosa", "flor"], query: ["rosa:*", "flor:*"]},
    { synonyms: ["strawberry", "fresa"], query: ["strawberr:*", "fresa:*"]},
    { synonyms: ["vegetal", "de soya"], query: ["vegetal", "de & soya"], complex: ["soya"]},
    { synonyms: ["soy", "soya", "china"], query: ["soy", "soya", "china"], id: "soya"},
    { synonyms: ["avocado", "aguacate"], query: ["avocado:*", "aguacate:*"]},
    { synonyms: ["oil", "aceite"], query: ["oil:*", "aceite:*"]},
    { synonyms: ["cider", "sidra"], query: ["sider", "sidra"]},
    { synonyms: ["walnut", "nuez", "nues", "nut"], query: ["wanut:*", "nuez:*", "nues:*", "nut"]},
    { synonyms: ["cherry", "cereza", "ceresa", "cherrie"], query: ["cherry", "cherries", "cerez:*", "ceres:*"]},
    { synonyms: ["grape", "uva", "grappe"], query: ["grape:*", "uva:*", "grappe"]},
    { synonyms: ["apple", "manzana", "mansana"], query: ["apple:*", "manzan:*", "mansan:*"]},
    { synonyms: ["raspberry", "frambuesa", "raspb"], query: ["raspb:*", "frambue:*"]},
    { synonyms: ["pineapple", "pina"], query: ["pineapple:*", "pina:*"]},
    { synonyms: ["funda", "sobre", "bolsa", "paquete", "paq", "pack", "bag", "saco", "fda"], query: ["funda", "sobre", "bolsa", "paquete", "paq", "pack:*", "bag", "saco", "fda"]},
    { synonyms: ["imp", "importado", "importada"], query: ["imp:*"]},
    { synonyms: ["leche", "milk", "alimento lacteo", "alim lacteo"], query: ["leche", "milk:*", "lacteo:*", "lactea:*"], id: "leche"},
    { synonyms: ["entero", "entera", "full", "whole"], query: ["enter:*", "full", "whole"], id: "entero"},
    { synonyms: ["leche entera", "leche liquida", "leche entero", "leche liquido"], query: ["leche & entera", "leche & liquida"], complex: ["leche", "liquido"] },
    { synonyms: ["fortigrow", "crecimiento", "fortificada"], query: ["forti:*", "crecimien:*"]},
    { synonyms: ["balsamic", "balsamico", "balsamica"], query: ["balsamic:*"]},
    { synonyms: ["ranchero", "ranchera"], query: ["rancher:*", "baldo:*"]},
    { synonyms: ["sazon", "adobo"], query: ["sazon", "adobo"]},
    { synonyms: ["one", "uno", "1"], query: ["one", "uno", "1"], id: "1"},
    { synonyms: ["two", "dos", "2"], query: ["two", "dos", "2"], id: "2"},
    { synonyms: ["three", "tres", "3"], query: ["three", "tres", "3"], id: "3"},
    { synonyms: ["four", "cuatro", "4"], query: ["four", "cuatro", "4"], id: "4"},
    { synonyms: ["five", "cinco", "5"], query: ["five", "cinco", "5"], id: "5"},
    { synonyms: ["six", "seis", "6"], query: ["six", "seis", "6"], id: "6"},
    { synonyms: ["seven", "siete", "7"], query: ["seven", "siete", "7"], id: "7"},
    { synonyms: ["eight", "ocho", "8"], query: ["eight", "ocho", "8"], id: "8"},
    { synonyms: ["nine", "nueve", "9"], query: ["nine", "nueve", "9"], id: "9"},
    { synonyms: ["thousand", "mil", "1000"], query: ["thousand", "mil", "1000"], id: "1000"},
    { synonyms: ["duo", "doble", "2 en 1"], query: ["duo", "doble", "2 & en & 1"], complex: ["2"]},
    { synonyms: ["powder", "polvo"], query: ["powder", "polvo"]},
    { synonyms: ["de coccion", "para cocinar", "de cocinar", "cocina"], query: ["coccio:*", "cocina:*"]},
    { synonyms: ["nutmeg", "nuez moscada"], query: ["nutmeg:*", "nuez & moscada"]},
    { synonyms: ["pink", "rosado", "rosada"], query: ["pink:*", "rosad:*", "rosa"], id: "pink"},
    { synonyms: ["himalaya", "sal rosada", "himalayan"], query: ["himalaya:*"], complex: ["sal", "pink"]},
    { synonyms: ["pimienta", "pimiento", "pepper"], query: ["pimient:*", "pepper"], id: "pimienta"},
    { synonyms: ["paprika", "pimenton"], query: ["paprika:*", "pimento:*"]},
    { synonyms: ["colores", "tricolor"], query: ["colore:*", "tricolor:*"], id: "colores"},
    { synonyms: ["pimiento variado", "pimientos variado"], query: ["pimient:* & variado:*"], complex: ["pimienta", "colores"]},
    { synonyms: ["sea", "marino", "marina", "de mar"], query: ["sea", "marino", "marina", "de & mar"]},
    { synonyms: ["coarse", "gruesa", "grueso"], query: ["coarse", "grues:*"]},
    { synonyms: ["greenland", "lucas perez"], query: ["greenland", "lucas & perez"]},
    { synonyms: ["frosting", "glaseado", "glaseada"], query: ["frosting", "glaseado"]},
    { synonyms: ["chip", "chispa"], query: ["chisp:*", "chip:*"]},
    { synonyms: ["cour cereale", "cuor di cereale"], query: ["cereal:*"]},
    { synonyms: ["musclemilk", "muscle milk"], query: ["musclemilk:*", "muscle & milk"]},
    { synonyms: ["bioeva", "bio eva"], query: ["bioeva:*", "bio & eva"]},
    { synonyms: ["medie", "mediano", "mediana"], query: ["medie", "median:*"]},
    { synonyms: ["ketchup", "catchup"], query: ["ketchup", "catchup"]},
    { synonyms: ["lasagne", "lasagna", "lasana"], query: ["lasagn:*", "lasana"]},
    { synonyms: ["linguine", "linguini"], query: ["linguin:*"]},
    { synonyms: ["squeeze", "dispenser", "dispensador"], query: ["squeez:*", "dispens:*"]},
    { synonyms: ["spaguetti", "espaguetti", "espagueti", "spaghetti", "spagetti", "espagheti"], query: ["espag:*", "spag:*"]},
    { synonyms: ["baking", "hornear"], query: ["baking:*", "hornear:*"]},
    { synonyms: ["edulcorante", "endulzante"], query: ["edulcorante", "endulzante"]},
    { synonyms: ["sugar", "azucar", "sug"], query: ["azucar", "sug:*", "a"], id: "azucar"},
    { synonyms: ["azucar refinada", "azucar refino", "azucar refina", "azucar refinado"], query: ["azucar & refin:*"], complex: ["azucar", "white"]},
    { synonyms: ["diet", "dietetica", "dietetico", "dieta"], query: ["diet:*", "sin & azucar", "zero & sugar", "bajo & azucar"], id: "diet"},
    { synonyms: ["stevia"], query: ["stevia"], complex: ["azucar", "diet"]},
    { synonyms: ["salami", "salame"], query: ["salam:*"], id: "salami"},
    { synonyms: ["olive", "aceituna"], query: ["olive:*", "aceitun:*"]},
    { synonyms: ["pickle", "encurtido", "encurtida", "pickled"], query: ["pickle:*", "encurtid:*"]},
    { synonyms: ["baby", "bebe"], query: ["bab:*", "bebe:*"]},
    { synonyms: ["bean", "habichuela", "frijole", "frijol"], query: ["bean:*", "habichuela:*", "frijol:*"], id: "habichuela"},
    { synonyms: ["vainita", "habichuelas tiernas"], query: ["vainita", "habichuela:* & tiern:*"], complex: ["habichuela", "verde"]},
    { synonyms: ["tomato", "tomate"], query: ["tomat:*"], id: "tomate"},
    { synonyms: ["light", "lightly", "lighty", "lite", "ligera", "ligero", "menos", "reduced", "reducida", "reducido", "bajo", "baja", "low", "con poco", "con pocos", "con poca", "con pocas", "poca"], query: ["light:*", "lite", "liger:*", "menos", "reduc:*", "bajo:*", "baja", "low:*", "con & poca", "con & poco"]},
    { synonyms: ["hongo", "champinon", "mushroom"], query: ["hongo:*", "champinon:*", "mushroom:*"]},
    { synonyms: ["meat", "carne"], query: ["meat:*", "carn:*"]},
    { synonyms: ["french", "france", "francesa"], query: ["french", "france:*"]},
    { synonyms: ["basil", "albahaca", "basilico"], query: ["basil:*", "albahaca"]},
    { synonyms: ["original", "tradicional", "regular", "classic", "clasica", "clasico"], query: ["original", "tradicional", "regular", "classic:*", "clasic:*"]},
    { synonyms: ["fat", "grasa"], query: ["fat", "grasa:*"], id: "grasa"},
    { synonyms: ["libre de grasa"], query: ["libre & de & grasa"], complex: ["sin", "grasa"]},
    { synonyms: ["reddi whip", "reddi wip"], query: ["reddi & whip", "reddi & wip"]},
    { synonyms: ["vegetale", "verdura"], query: ["vegetale:*", "verdura:*"]},
    { synonyms: ["heart", "corazon"], query: ["heart:*", "corazon:*"]},
    { synonyms: ["palmito", "palm"], query: ["palm:*"]},
    { synonyms: ["ajo", "garlic"], query: ["ajo", "garlic"], id: "ajo"},
    { synonyms: ["al ajillo"], query: ["al & ajillo"], complex: ["con", "ajo"]},
    { synonyms: ["hueso", "bone", "espina"], query: ["hueso", "bone", "esp:*"], id: "hueso"},
    { synonyms: ["deshuesada", "deshuesado", "spineless"], query: ["deshuesad:*", "spineless"], complex: ["sin", "hueso"]},
    { synonyms: ["onion", "cebolla"], query: ["onion", "ceboll:*"]},
    { synonyms: ["roasted", "tostado", "asado", "rostizado", "rostizada", "asada", "tostada", "toasted"], query: ["roasted:*", "tostad:*", "toaste:*", "asad:*", "rostizad:*"]},
    { synonyms: ["con sabor", "con sabor a", "sabor a"], query: ["sabor"]},
    { synonyms: ["chestnut", "castana"], query: ["chestnut:*", "castana"]},
    { synonyms: ["inut", "imperial nuts", "implerial nuts"], query: ["inut:*", "imperial:* & nut:*", "implerial:* & nut:*"]},
    { synonyms: ["cacao", "chocolate", "choco", "choc"], query: ["cacao", "cocoa", "choco:*", "choc"]},
    { synonyms: ["kitkat", "kit kat"], query: ["kit & kat", "kitkat"]},
    { synonyms: ["mym", "m&m", "m m", "mm"], query: ["m&m", "m <-> m", "mm", "mym"]},
    { synonyms: ["kiss", "beso", "besito", "kisse"], query: ["kiss:*", "beso:*", "besit:*"]},
    { synonyms: ["teddy", "osito", "bear"], query: ["tedd:*", "osit:*", "bear:*", "oso"]},
    { synonyms: ["chicle", "goma de mascar", "goma mascar", "chiclet", "bubble gum", "chewing gum"], query: ["chicl:*", "goma & mascar", "bubble & gum", "chewing & gum"]},
    { synonyms: ["chalaca", "caramelo barrilete"], query: ["caramelo & barrilete", "chalaca"]},
    { synonyms: ["style", "estilo"], query: ["style", "estilo"]},
    { synonyms: ["teeth", "diente"], query: ["teeth", "diente"]},
    { synonyms: ["american", "americano", "americana"], query: ["american:*"]},
    { synonyms: ["italian", "italiano", "italiana"], query: ["italian:*"]},
    { synonyms: ["aleman", "german"], query: ["aleman", "german"]},
    { synonyms: ["mexico", "mexican", "mexicana", "mexicano", "mexi"], query: ["mexi:*"]},
    { synonyms: ["argentino", "argentina", "argentinean"], query: ["argentin:*"]},
    { synonyms: ["chileno", "chilena", "chilean"], query: ["chilean:*", "chilen:*"]},
    { synonyms: ["brasileno", "brasilena", "brazilian", "brasilian"], query: ["brasil:*", "brazil:*"]},
    { synonyms: ["popcorn", "palomita", "pop corn"], query: ["popcorn:*", "palomita:*", "pop & corn"]},
    { synonyms: ["rice", "arroz"], query: ["rice", "arroz"]},
    { synonyms: ["gelatina oli"], query: ["gelatina & oli", "geltaina & baldom"]},
    { synonyms: ["carrot", "zanahoria"], query: ["carrot:*", "zanahori:*"] },
    { synonyms: ["ice cream", "helado"], query: ["ice & cream", "helado"]},
    { synonyms: ["lyptus", "eucalipto"], query: ["lyptu:*", "eucalipt:*"]},
    { synonyms: ["menthol", "mentol"], query: ["mentho:*", "mentol:*"]},
    { synonyms: ["orange", "naranja", "mamey"], query: ["orange:*", "naranja:*", "mamey"], id: "naranja"},
    { synonyms: ["marshmallow", "malvavisco", "malvabisco", "marsh", "Malvacisco"], query: ["marsh:*", "malvavisc:*", "malvabisc:*", "malvacisco"]},
    { synonyms: ["sirop", "jarabe", "syrop", "syrup"], query: ["sirop", "jarabe", "syrop", "syrup"]},
    { synonyms: ["potato", "papa"], query: ["potat:*", "papa:*"]},
    { synonyms: ["frie", "frita", "frito"], query: ["frie:*", "frit:*"]},
    { synonyms: ["sour", "agrio", "agria", "amargo", "amarga", "acido", "acida"], query: ["sour", "agri:*", "amarg:*", "acid:*"], complex: ["sin", "azucar"]},
    { synonyms: ["black", "negro", "negra", "moreno", "morena", "dark", "oscuro", "oscura"], query: ["black", "negro:*", "negra:*", "morena:*", "moreno:*", "dark", "oscuro", "oscura"]},
    { synonyms: ["blue", "azul"], query: ["blue", "azul:*"]},
    { synonyms: ["arveja", "chicharo", "green pea"], query: ["arveja", "chicharo", "green & pea"]},
    { synonyms: ["lentil", "lenteja", "masoor dal"], query: ["lentil", "lenteja", "masoor <-> dal"]},
    { synonyms: ["dry", "seco", "seca"], query: ["dry", "seco", "seca"]},
    { synonyms: ["fibra", "integral"], query: ["fibra", "integral", "!integral & brown", "!integral & marron"]},
    { synonyms: ["galleta danesa", "galletas danesas", "galletas danesa", "galleta estilo danesa", "galleta de mantequilla"], query: ["galleta:* & danesa:*"], complex: ["galleta", "mantequilla"]},
    { synonyms: ["cookie butter", "crema de galleta", "crema de galletas", "crema galleta", "crema galletas"], query: ["cookie & butter"], complex: ["cream", "galleta"]},
    { synonyms: ["dietalat", "descremada", "descremado"], query: ["dietalat", "descremad:*"]},
    { synonyms: ["turkey", "pavo"], query: ["turkey", "pavo"]},
    { synonyms: ["gluten"], query: ["gluten"], id: "gluten"},
    { synonyms: ["s gluten"], query: ["s & gluten"], complex: ["sin", "gluten"]},
    { synonyms: ["salsa", "sauce", "sausage"], query: ["salsa", "sauce", "sausage"], id: "salsa"},
    { synonyms: ["salsa de tomate", "salsa de tomates", "pasta de tomate", "pasta de tomates"], query: ["pasta & tomate"], complex: ["salsa", "tomate"]},
    { synonyms: ["wheat", "trigo"], query: ["wheat", "trigo"]},
    { synonyms: ["codito", "elbow"], query: ["codito:*", "elbow:*"]},
    { synonyms: ["aunt jemima", "pearl milling company", "pearl milling"], query: ["aunt & jemima", "pearl & milling"]},
    { synonyms: ["pepinillo", "gherkin"], query: ["pepinill:*", "gherkin"], id: "pepinillo"},
    { synonyms: ["sweet relish"], query: ["sweet & relish"], complex: ["pepinillo", "dulce"]},
    { synonyms: ["refri", "refried", "refrito", "refrita"], query: ["refri:*"]},
    { synonyms: ["cuscu", "couscou", "cous cous"], query: ["cuscu:*", "couscou:*", "cous & cous"]},
    { synonyms: ["canellinni", "cannellini", "canellini", "alubia"], query: ["canellin:*", "cannellini", "alubia"]},
    { synonyms: ["carita", "lobia"], query: ["carita", "lobia"]},
    { synonyms: ["cebada", "barley"], query: ["cebada", "barley"]},
    { synonyms: ["saborizante", "bebida en polvo"], query: ["saborizante", "bebida & polvo"]},
    { synonyms: ["amarillo", "amarilla", "yellow"], query: ["amarill:*", "yellow"]},
    { synonyms: ["picado", "picada", "granulado", "granulada", "triturado", "triturada"], query: ["picad:*", "granulad:*", "triturad:*"]},
    { synonyms: ["pinone", "pine nuts", "pine nut"], query: ["pine & nut:*", "pinone:*"]},
    { synonyms: ["rosemary", "romero"], query: ["rosemary", "romero"]},
    { synonyms: ["hinojo", "fennel"], query: ["hinojo", "fennel"]},
    { synonyms: ["tilo", "linden"], query: ["tilo", "linden"]},
    { synonyms: ["celery", "apio"], query: ["celery", "apio"]},
    { synonyms: ["arco iris", "arcoiris", "rainbow"], query: ["arco & iris", "arcoiris", "rainbow"]},
    { synonyms: ["canelone", "canelon", "cannelloni"], query: ["canelon:*", "cannelloni:*"]},
    { synonyms: ["prosciu", "prosciutto"], query: ["prosciu:*"]},
    { synonyms: ["macarron", "macarrone", "macaroni"], query: ["macarron:*", "macaron:*"]},
    { synonyms: ["shell", "caracol", "caracolito"], query: ["shell:*", "caracol:*"]},
    { synonyms: ["salsa bechamel"], query: ["salsa & bechamel"], complex: ["salsa", "white"]},
    { synonyms: ["alfred", "alfredo"], query: ["alfred:*"]},
    { synonyms: ["sodio", "sodium"], query: ["sodio", "sodium"], complex: ["sal"]},
    { synonyms: ["strong", "fuerte"], query: ["strong", "fuerte"]},
    { synonyms: ["marron", "brown"], query: ["marron", "brown"]},
    { synonyms: ["tahiti", "tahini"], query: ["tahiti", "tahini"]},
    { synonyms: ["broth", "sopa"], query: ["broth", "sopa", "caldo"]},
    { synonyms: ["sopita", "caldo"], query: ["sopita", "caldo"]},
    { synonyms: ["papita"], query: ["papita", "papa:* & frita:*"]},
    { synonyms: ["shrim", "shrimp", "camaron"], query: ["shrim:*", "camaron:*"]},
    { synonyms: ["beef", "res"], query: ["beef", "res"]},
    { synonyms: ["arequipe", "dulce de leche"], query: ["arequipe"], complex: ["dulce", "leche"] },
    { synonyms: ["alpina", "alpe"], query: ["alpe", "alpina"]},
    { synonyms: ["nib", "pepita", "punta"], query: ["nib", "pepita", "punta"]},
    { synonyms: ["cafe", "coffee"], query: ["cafe", "coffee", "!cafe & espresso", "!cafe & mocha", "!cafe & cappuc:*", "!cafe & latte"]},
    { synonyms: ["baldom"], query: ["baldom", "!baldom & ranchero"]},
    { synonyms: ["xbar", "x bar"], query: ["xbar", "x <-> bar"]},
    { synonyms: ["dulce especial jomisardys", "dulce de leche jomisardys", "dulce leche jomisardys"], query: ["dulce & especial & jomisardys", "dulce & leche & jomisardys"]},
    { synonyms: ["guandy"], query: ["guandy", "!guandy & tropical"]},
    { synonyms: ["worm", "gusano", "glowworm", "gusanito", "caterpillar", "squiggle"], query: ["worm:*", "gusan:*", "glowworm", "caterpillar", "squiggle"]},
    { synonyms: ["caramelo"], query: ["caramelo", "dulce & !caramelo", "menta & !caramelo"]},
    { synonyms: ["papaya", "lechosa"], query: ["lechosa", "papaya"]},
    { synonyms: ["snake", "culebra", "culebrita"], query: ["snake:*", "culebra:*"]},
    { synonyms: ["digestive", "digestivo", "digestiva"], query: ["digestiv:*"]},
    { synonyms: ["barquillo", "barquilla", "barq"], query: ["barquill:*"]},
    { synonyms: ["tutifruti", "tuttifruti", "tutti frutti"], query: ["tutifruti", "tuttifruti", "tutti & frut:*"]},
    { synonyms: ["natuchips", "platanito"], query: ["natuchips", "platanito"]},
    { synonyms: ["cajuil", "cashew"], query: ["cajuil", "cashew"]},
    { synonyms: ["energy", "energetico", "energetica"], query: ["energy", "energetic:*"]},
    { synonyms: ["sunflower", "girasol"], query: ["sunflower", "girasol"]},
    { synonyms: ["taco", "tortilla"], query: ["taco", "tortilla"]},
    { synonyms: ["alcarrapa", "caper"], query: ["alcarrapa", "caper"]},
    { synonyms: ["cmate", "coffee mate"], query: ["cmate", "coffee & mate"]},
    { synonyms: ["ginger", "jengibre"], query: ["ginger", "jengibre"]},
    { synonyms: ["baking soda", "bicarbonato"], query: ["baking & soda", "bicarbonato"]},
    { synonyms: ["puddin", "pudin", "pudding"], query: ["puddin:*", "pudin:*"]},
    { synonyms: ["ocean s", "ocean spray"], query: ["ocean & s", "ocean & spray"]},
    { synonyms: ["mrs cubbison", "mrs c"], query: ["mrs & cubbison", "mrs & c"]},
    { synonyms: ["cacaito", "copitta", "copita"], query: ["cacaito", "copitta", "copita"]},
    { synonyms: ["tarro", "lata"], query: ["tarro", "lata"]},
    { synonyms: ["icebreakers", "ice breakers"], query: ["icebreakers", "ice & breakers"]},
    { synonyms: ["ghirardelli", "ghir"], query: ["ghirardelli", "ghir"]},
    { synonyms: ["gomita", "gajo", "gummy"], query: ["gomita", "gajo", "gummy"]},
    { synonyms: ["octopus", "pulpo"], query: ["octopus", "pulpo"]},
    { synonyms: ["yolada", "iodized"], query: ["yolada", "iodized"]},
    { synonyms: ["caramelized", "caramelizado", "caramelizada"], query: ["caramelizad:*", "caramelized"]},
    { synonyms: ["seasoned", "seasoning", "sazonado", "sazonada", "condimentada", "condimentado"], query: ["seasoned:*", "seasoning", "sazonad:*", "condimentad:*"]},
    { synonyms: ["dressing", "aderezo"], query: ["dressing", "aderezo"]},
    { synonyms: ["mostaza", "mustard"], query: ["mostaza", "mustard"]},
    { synonyms: ["island", "isla"], query: ["island", "isla"]},
    { synonyms: ["wishbone", "wish bone"], query: ["wish & bone", "wishbone"]},
    { synonyms: ["mayonnaise", "mayonesa", "mayo"], query: ["mayonnaise", "mayonesa", "mayo"]},
    { synonyms: ["a-1", "a1"], query: ["a-1", "a1"]},
    { synonyms: ["sparking", "con gas", "gasificada", "gasificado", "sparkling", "carbonatada", "carbonatado"], query: ["sparking", "sparkling", "con & gas", "gasificad:*", "carbonatad:*"], id: "sparkling"},
    { synonyms: ["agua", "water"], query: ["agua", "water"]},
    { synonyms: ["club soda"], query: ["club & soda"], complex: ["agua", "sparkling"]},
    { synonyms: ["cristal", "crystal"], query: ["cristal", "crystal"]},
    { synonyms: ["limonada", "lemonade"], query: ["limonada", "lemonade"], complex: ["jugo", "limon"]},
    { synonyms: ["cana del caribe", "cdc"], query: ["cana & del & caribe", "cdc"]},
    { synonyms: ["gaseosa", "soda", "refresco"], query: ["gaseosa", "soda", "refresco"], id: "gaseosa"},
    { synonyms: ["maracuya", "passion fruit", "chinola"], query: ["maracuya", "passion & fruit", "chinola"]},
    { synonyms: ["ruby red", "toronja", "grapefruit", "pompelmo"], query: ["ruby & red", "toronja", "grapefruit", "pompelmo"]},
    { synonyms: ["oceanspray", "ocean spray"], query: ["oceanspray", "ocean & spray"]},
    { synonyms: ["gatorade", "gatorlyte"], query: ["gatorade", "gatorlyte"]},
    { synonyms: ["jugo ya", "ya jugo"], query: ["jugo & ya", "naranya", "naranjaya", "mangoya", "pinaya", "chinolaya", "tropicalya", "fresaya", "guanabanaya", "morisonandoya", "limonya", "cerezaya", "champolaya"]},
    { synonyms: ["champola", "guanabana"], query: ["champola", "guanabana"]},
    { synonyms: ["fruit punch", "coctel de frutas"], query: ["fruit & punch", "coctel & fruta*"]},
    { synonyms: ["s bernardo", "san bernardo", "sanbernardo"], query: ["san & bernardo", "s & bernardo", "sanbernardo"]},
    { synonyms: ["lacroix", "la croix"], query: ["lacroix", "la & croix"]},
    { synonyms: ["aranciata"], query: ["aranciata"], complex: ["gaseosa", "naranja"]},
    { synonyms: ["san pellegrino", "sanpellegrino", "s pellegrino"], query: ["san & pellegrino", "sanpellegrino", "s & pellegrino"]},
    { synonyms: ["lowenbraw", "lowenbrau"], query: ["lowenbra:*"]},
    { synonyms: ["nectar", "concentrado"], query: ["nectar", "concentrad:*"]},
    { synonyms: ["watermelon", "sandia"], query: ["watermelon:*", "sandia:*"]},
    { synonyms: ["clamato", "clomato"], query: ["clamato", "clomato"]},
    { synonyms: ["smothie", "batido", "batida", "smoothie"], query: ["smothie", "smoothie", "batid:*"]},
    { synonyms: ["aloe vera", "sabila", "aloe"], query: ["aloe & vera", "sabila", "aloe"]},
    { synonyms: ["beer", "cerveza"], query: ["beer", "cerveza"]},
    { synonyms: ["welch s", "welchs", "welch"], query: ["welch & s", "welchs", "welch"]},
    { synonyms: ["granada", "pomegranate"], query: ["granada", "pomegranate"]},
    { synonyms: ["vive100", "vive 100"], query: ["vive & 100"]},
    { synonyms: ["j p chenet", "jp chenet"], query: ["j & p & chenet", "jp & chenet"]},
    { synonyms: ["etiqueta", "label"], query: ["etiqueta", "label"]},
    { synonyms: ["coronita", "corona"], query: ["coronita", "corona"]},
    { synonyms: ["limitado", "limitada", "limited"], query: ["limitad:*", "limited"]},
    { synonyms: ["stolichnaya", "stoli"], query: ["stolichnaya", "stoli"]},
    { synonyms: ["puntacana", "punto cana"], query: ["puntacana", "punto & cana"]},
    { synonyms: ["sta", "santa"], query: ["sta", "santa"]},
    { synonyms: ["foil", "aluminio"], query: ["foil", "aluminio"]},
    { synonyms: ["tealight", "velita"], query: ["tealight", "velita"]},
    { synonyms: ["dishwasher", "lavavajillas"], query: ["dishwasher", "lavavajillas", "maquina & lavaplatos"]},
    { synonyms: ["toalla", "pano", "wipe", "toallita", "papel higienico humedo"], query: ["toalla", "pano", "wipe", "toallita", "papel & higienico & humedo"]},
    { synonyms: ["vela", "candle", "velon"], query: ["vela", "candle", "velon"]},
    { synonyms: ["bathroom", "bano", "bath"], query: ["bath:*", "bano"]},
    { synonyms: ["papel de bano", "papel higienico", "papel sanitario", "toalla higienica", "papel bano", "bano papel"], query: ["papel & bano", "papel & higienic:*", "papel & sanitario", "toalla & higienic:*"]},
    { synonyms: ["lavaplato", "jabon fregar", "jabon de fregar", "fregar jabon"], query: ["lavaplato", "jabon & fregar", "fregar & jabon"]},
    { synonyms: ["trapeador", "suaper"], query: ["trapeador", "suaper"]},
    { synonyms: ["plastico", "desechable"], query: ["plastico", "desechable"]},
    { synonyms: ["heavy", "pesado", "pesada"], query: ["heavy", "pesad:*"]},
    { synonyms: ["roach", "cucaracha"], query: ["roach", "cucaracha"]},
    { synonyms: ["hormiga", "ant"], query: ["hormiga", "ant"]},
    { synonyms: ["de tela", "para ropa"], query: ["de & tela", "para & ropa"]},
    { synonyms: ["scotchbrite", "scotch brite"], query: ["scotchbrite", "scotch & brite"]},
    { synonyms: ["fregador", "fregadero", "esponja"], query: ["fregador", "fregadero", "esponja"], id: "fregador"},
    { synonyms: ["metal", "metálico", "metalica", "metalica", "alambre"], query: ["metal", "metalic:*", "alambre"], id: "metal"},
    { synonyms: ["brillo", "estropajo", "brillador", "brilladora"], query: ["brillo", "estropajo", "brillador", "brilladora"], complex: ["fregador", "metal"]},
    { synonyms: ["calzado", "zapato", "shoe"], query: ["calzado", "zapato", "shoe"]},
    { synonyms: ["limpiador", "cleaner", "desinfectante", "desinfectante", "sanitizer"], query: ["limpiador", "cleaner", "desinfectant:*", "sanitizer"]},
    { synonyms: ["toilet", "inodoro"], query: ["toilet", "inodoro"], id: "inodoro"},
    { synonyms: ["hawaiian", "hawaiana", "hawaiano"], query: ["hawaiian", "hawaian:*"]},
    { synonyms: ["breeze", "brisa"], query: ["breeze", "brisa"]},
    { synonyms: ["cloro", "blanqueador", "bleach"], query: ["cloro", "blanquead:*", "bleach"]},
    { synonyms: ["x treme", "xtreme", "extremo", "maximo", "maxima"], query: ["x & treme", "xtreme", "extrem:*", "maxim:*"]},
    { synonyms: ["fragancia", "aroma"], query: ["fragancia", "aroma"]},
    { synonyms: ["antiadherent", "antiadherente", "non stick"], query: ["antiadherent:*", "non & stick"]},
    { synonyms: ["d scaline", "d scalin", "dscalin"], query: ["d & scaline", "d & scalin", "dscalin"]},
    { synonyms: ["lavander", "lavanda", "lavender"], query: ["lavander", "lavanda", "lavender"]},
    { synonyms: ["air wick", "airwick"], query: ["air & wick", "airwick"]},
    { synonyms: ["aparato", "device", "electrico", "electrica", "maquina"], query: ["aparato", "device", "electric:*", "maquina"], id: "aparato"},
    { synonyms: ["oxiclean", "oxi clean"], query: ["oxiclean", "oxi & clean"]},
    { synonyms: ["storage", "almacenar", "almacenamiento"], query: ["storage", "almacenar", "almacenamiento"]},
    { synonyms: ["snack", "picadera", "bocadillo"], query: ["snack", "picadera", "bocadillo"]},
    { synonyms: ["bolsillo", "pocket"], query: ["bolsillo", "pocket"]},
    { synonyms: ["sorbete", "calimete"], query: ["sorbete", "calimete"], id: "sorbete"},
    { synonyms: ["plastifar"], query: ["plastifar"], id: "plastifar"},
    { synonyms: ["sorbete plastifar", "removedor plastifar"], query: ["sorbete & plastifar", "removedor & plastifar"], complex: ["sorbete", "plastifar"]},
    { synonyms: ["linen", "lino"], query: ["linen", "lino"]},
    { synonyms: ["coastal", "costal"], query: ["coastal", "costal"]},
    { synonyms: ["destapador", "succionador", "sucionador", "destupidor"], query: ["destapador", "succionador", "sucionador", "destupidor"], id: "destapador"},
    { synonyms: ["destapacano", "destapabano"], query: ["destapacano", "destapabano"], complex: ["destapador", "inodoro"]},
    { synonyms: ["citrica", "citrico", "citrus"], query: ["citrica", "citrico", "citrus", "naranja", "orange"], complex: ["limon"]},
    { synonyms: ["quemador", "calentador", ], query: ["quemador", "calentador"], complex: ["aparato"]},
    { synonyms: ["wood", "madera"], query: ["wood", "madera"]},
    { synonyms: ["palillo", "pincho", "toothpick", "skewer", "broncheta"], query: ["palill:*", "pinch:*", "toothpick", "skewer", "broncheta"]},
    { synonyms: ["removedor", "remover"], query: ["removedor", "remover"], id: "removedor"},
    { synonyms: ["mancha", "stain"], query: ["mancha", "stain"], id: "mancha"},
    { synonyms: ["desmanchador", "desmanchadora", "quitamacha", "quitamancha"], query: ["desmanchador", "desmanchadora"], complex: ["removedor", "mancha"]},
    { synonyms: ["absorvente", "absorbente", "absorvedor", "reductor"], query: ["absorvente", "absorbente", "absorvedor", "reductor"], id: "absorvente"},
    { synonyms: ["humedad", "humidity"], query: ["humedad", "humidity"], id: "humedad"},
    { synonyms: ["deshumidificador", "deshumificador"], query: ["deshumidificador", "deshumificador"], complex: ["absorvente", "humedad"]},
    { synonyms: ["cuchara", "spoon"], query: ["cuchara", "spoon"]},
    { synonyms: ["tenedor", "fork"], query: ["tenedor", "fork"]},
    { synonyms: ["cuchillo", "knife"], query: ["cuchillo", "knife"]},
    { synonyms: ["repelente", "cintronela", "citronela", "repellent"], query: ["repelente", "citronela", "cintronela", "repellent"]},
    { synonyms: ["multiuso", "multi uso", "all purpose", "allpurpose", "multipurpose", "multi purpose"], query: ["multiuso", "multi & uso", "all & purpose", "allpurpose", "multipurpose", "multi & purpose", "multi:*"]},
    { synonyms: ["mold", "moho"], query: ["mold", "moho"]},
    { synonyms: ["kitchen", "cocina"], query: ["kitchen", "cocina"]},
    { synonyms: ["pet", "mascota"], query: ["pet", "mascota"]}
]; 

function pluralizeWord(word: string) {
  if (
    word.includes("&") ||
    word.length === 1 ||
    STOP_WORDS.includes(word) ||
    PERMITED_STOP_WORDS.includes(word)
  ) {
    return [word];
  }
  const variants = new Set<string>();
  variants.add(word);
  const pluralized = plural(word);
  if (pluralized !== word) variants.add(pluralized);
  const pluralizedEs = pluralizeEs(word);
  if (pluralizedEs !== word) variants.add(pluralizedEs);
  return [...variants];
}

const baseV2 = base.map(({ synonyms, query, id, complex }) => {
  const expandedSynonyms = Array.from(
    new Set(
      synonyms.flatMap((syn) => pluralizeWord(syn))
    )
  );
  return { synonyms: expandedSynonyms, query, id, complex };
});

export { baseV2 };
